"""scrape_jobs: cola de trabajos para el scraper de politica

Revision ID: 0436fbef10e9
Revises: eb1a1e0e15a2
Create Date: 2026-08-05 01:20:04.038859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0436fbef10e9'
down_revision: Union[str, Sequence[str], None] = 'eb1a1e0e15a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('per_source_cap', sa.Integer(), nullable=False),
    sa.Column('analyzer_name', sa.String(length=40), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('crawl_run_id', sa.Integer(), nullable=True),
    sa.Column('progress_json', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_correlation_id'), 'scrape_jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_crawl_run_id'), 'scrape_jobs', ['crawl_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_jobs_crawl_run_id'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_correlation_id'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    # ### end Alembic commands ###
