"""baseline: esquema actual (articles, entities, entity_aliases)

Revision ID: 716c8e4a7513
Revises:
Create Date: 2026-08-03 09:01:43.702321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716c8e4a7513'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('section', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('main_topic', sa.String(length=200), nullable=True),
    sa.Column('topic_keywords', sa.String(length=600), nullable=True),
    sa.Column('overall_sentiment', sa.String(length=10), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('framing', sa.String(length=40), nullable=True),
    sa.Column('headline_intent', sa.String(length=20), nullable=True),
    sa.Column('lead_orientation', sa.String(length=20), nullable=True),
    sa.Column('dominant_actor', sa.String(length=300), nullable=True),
    sa.Column('source_quality', sa.String(length=30), nullable=True),
    sa.Column('has_hard_data', sa.Boolean(), nullable=True),
    sa.Column('blamed_actor', sa.String(length=300), nullable=True),
    sa.Column('credited_actor', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_articles_source'), 'articles', ['source'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('alias_key', sa.String(length=100), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_key', 'type', name='uq_alias_per_type')
    )
    op.create_index(op.f('ix_entity_aliases_alias_key'), 'entity_aliases', ['alias_key'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('mentions_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_toward', sa.String(length=10), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'name', 'type', name='uq_entity_per_article')
    )
    op.create_index(op.f('ix_entities_article_id'), 'entities', ['article_id'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_article_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_entity_aliases_alias_key'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_articles_source'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
