/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Entrega un JWT si las credenciales coinciden con las del entorno.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Valida el token guardado en el navegador al abrir la aplicación.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Encola el análisis de la URL (§3.1 de task.md): la descarga y el NLP
         *     corren en segundo plano en vez de bloquear el request hasta 60s. Si la
         *     URL ya estaba guardada, devuelve `200` con el registro directamente (no
         *     hay nada que encolar). Si es nueva, devuelve `202` + `job_id`; el cliente
         *     consulta el resultado con GET /api/jobs/{job_id}.
         */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Estado/resultado de un job de POST /api/analyze.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Articles
         * @description Lista reportes guardados con filtros combinables. Devuelve resúmenes
         *     (sin cuerpo ni entidades detalladas); usa GET /api/articles/{id} para el
         *     reporte completo.
         */
        get: operations["list_articles_api_articles_get"];
        put?: never;
        /**
         * Save Article
         * @description Persiste el resultado de /api/analyze, ya revisado/corregido.
         */
        post: operations["save_article_api_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Article Filters
         * @description Valores disponibles para poblar los selectores de filtro del frontend.
         *     Fuentes y secciones son dinámicas (dependen de lo ya guardado); el resto
         *     de campos de encuadre son enumeraciones fijas del análisis.
         */
        get: operations["article_filters_api_articles_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Article
         * @description Reporte completo (con entidades) de un artículo ya guardado.
         */
        get: operations["get_article_api_articles__article_id__get"];
        /**
         * Update Article
         * @description Rectifica el análisis de un artículo ya guardado (§8.2): tema, encuadre,
         *     sentimiento, actores señalados... Solo toca los campos enviados. No permite
         *     corregir `title`/`body`/`url` porque eso es lo que decía la fuente, no un
         *     juicio del sistema — si el scrape en sí está mal, hay que borrar y volver a
         *     analizar.
         */
        put: operations["update_article_api_articles__article_id__put"];
        post?: never;
        /**
         * Delete Article
         * @description Borra permanentemente un artículo y sus menciones (§8.2): no hay
         *     archivado ni papelera — es el procedimiento de borrado que el cliente
         *     puede exigir sobre su propio contenido o el de una persona nombrada.
         */
        delete: operations["delete_article_api_articles__article_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Entity
         * @description Rectifica una mención puntual (§8.2): nombre mal extraído, sentimiento
         *     mal inferido... sin tener que borrar y re-analizar todo el artículo.
         *     Devuelve 409 si el cambio choca con otra mención ya existente en el mismo
         *     artículo (mismo nombre + tipo).
         */
        put: operations["update_entity_api_entities__entity_id__put"];
        post?: never;
        /**
         * Delete Entity
         * @description Borra una mención puntual (§8.2): redacta el juicio sobre una persona en
         *     UN artículo sin borrar el artículo completo.
         */
        delete: operations["delete_entity_api_entities__entity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Aliases */
        get: operations["list_aliases_api_aliases_get"];
        put?: never;
        /**
         * Create Alias
         * @description Crea un nuevo alias. Devuelve 409 si la sigla ya existe (mismo tipo).
         */
        post: operations["create_alias_api_aliases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aliases/{alias_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Alias
         * @description Actualiza parcialmente un alias (nombre canónico, estado activo/inactivo...).
         */
        put: operations["update_alias_api_aliases__alias_id__put"];
        post?: never;
        /**
         * Delete Alias
         * @description Elimina permanentemente un alias.
         */
        delete: operations["delete_alias_api_aliases__alias_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/canonical-entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Canonical Entities
         * @description Lista entidades canónicas (la dimensión "persona/organización real",
         *     no menciones por artículo) con cuántos artículos y menciones acumula cada
         *     una. Puede haber más de una fila para la misma figura real si se creó
         *     antes de que la heurística de nombre único las uniera ("Abinader" y
         *     "Luis Abinader" por separado) — usa POST .../merge para fusionarlas.
         */
        get: operations["list_canonical_entities_api_canonical_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/canonical-entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Canonical Entity
         * @description Detalle de una entidad canónica: sus datos y los artículos donde
         *     aparece vinculada (vía Entity.canonical_entity_id), más recientes primero.
         *     Esta es la respuesta confiable a "¿cuántos artículos hablan de esta
         *     persona?" — agrupa por identidad real, no por string de nombre.
         */
        get: operations["get_canonical_entity_api_canonical_entities__entity_id__get"];
        /**
         * Update Canonical Entity
         * @description Renombra y/o describe una entidad canónica. El nombre nuevo entra a
         *     `known_person_fullname_map()` en el siguiente análisis (ver
         *     analysis/canonicalize.py): la corrección se propaga hacia adelante, no
         *     solo en los reportes ya guardados. Devuelve 409 si el nombre nuevo choca
         *     con otra entidad canónica ya existente del mismo tipo — en ese caso hace
         *     falta fusionar (POST .../merge), no renombrar.
         */
        put: operations["update_canonical_entity_api_canonical_entities__entity_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/canonical-entities/{entity_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Canonical Entities
         * @description Fusiona `source_id` DENTRO de `entity_id`: reasigna todas las menciones
         *     (pasadas) que apuntaban a `source_id` y la borra. Es la corrección manual
         *     que el pipeline no puede inferir solo (dos nombres que en realidad son la
         *     misma figura, creados como filas separadas).
         */
        post: operations["merge_canonical_entities_api_canonical_entities__entity_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Crawl Runs
         * @description Historial de corridas del pipeline, más reciente primero.
         */
        get: operations["list_crawl_runs_api_crawl_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrape-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scrape Jobs
         * @description Corridas recientes, más reciente primero — el frontend la usa al
         *     montar la tab para detectar un job pending/running y retomar el polling
         *     en vez de mostrar el formulario (p. ej. tras recargar la página).
         */
        get: operations["list_scrape_jobs_api_scrape_jobs_get"];
        put?: never;
        /**
         * Start Scrape Job
         * @description Encola una corrida del scraper de política sobre las 9 fuentes
         *     permitidas. Rechaza con 409 si ya hay una en curso — un backend de un
         *     solo worker no tiene por qué correr dos scrapes de 9 fuentes a la vez.
         */
        post: operations["start_scrape_job_api_scrape_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrape-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scrape Job
         * @description Estado/avance de una corrida encolada por POST /api/scrape-jobs.
         */
        get: operations["get_scrape_job_api_scrape_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scrape-jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Scrape Job
         * @description Pide cancelar una corrida en curso. Cooperativo, no instantáneo:
         *     pipeline.run() solo lo consulta entre fuentes y entre artículos, así que
         *     puede tardar hasta que termine de descargar la fuente actual.
         */
        post: operations["cancel_scrape_job_api_scrape_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Chequeo real: si la BD no responde, `status` refleja el problema en
         *     vez de devolver "ok" incondicionalmente (antes lo hacía sin tocar la
         *     BD; un orquestador lo daría por sano mientras todo falla).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Métricas en formato Prometheus (§7.1 de task.md): pipeline, latencia y
         *     tasa de error por endpoint, llamadas/gasto de Gemini.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasPayload */
        AliasPayload: {
            /** Alias */
            alias: string;
            /** Canonical Name */
            canonical_name: string;
            /**
             * Type
             * @default ORG
             */
            type: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** AliasUpdatePayload */
        AliasUpdatePayload: {
            /** Alias */
            alias?: string | null;
            /** Canonical Name */
            canonical_name?: string | null;
            /** Type */
            type?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * AnalyzeAccepted
         * @description Respuesta de POST /api/analyze cuando la URL es nueva: el trabajo
         *     pesado (descarga + NLP, hasta ~60s) corre en segundo plano (§3.1 de
         *     task.md) en vez de bloquear el request. El cliente hace polling de
         *     GET /api/jobs/{job_id} hasta que `status` sea `done` o `failed`.
         */
        AnalyzeAccepted: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
        };
        /**
         * AnalyzePreviewEntity
         * @description Mención detectada en la vista previa: `id`/`canonical_entity_id` son
         *     `null` mientras el artículo no se guarde; si la URL ya estaba guardada
         *     (`AnalyzeResult.already_saved=True`), son los reales de esa fila.
         */
        AnalyzePreviewEntity: {
            /** Id */
            id: number | null;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Mentions Count */
            mentions_count: number;
            /** Sentiment Toward */
            sentiment_toward: string | null;
            /** Sentiment Score */
            sentiment_score: number | null;
            /** Context */
            context: string | null;
            /** Extraction Confidence */
            extraction_confidence: number;
            /** Canonical Entity Id */
            canonical_entity_id: number | null;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Url */
            url: string;
        };
        /**
         * AnalyzeResult
         * @description Respuesta de POST /api/analyze y del `result` de GET /api/jobs/{id}:
         *     o bien una vista previa recién analizada y sin guardar
         *     (`already_saved=False`, `id` `null`), o el artículo ya existente que se
         *     devuelve tal cual en vez de re-analizar (`already_saved=True`, `id` real).
         */
        AnalyzeResult: {
            /**
             * Already Saved
             * @default false
             */
            already_saved: boolean;
            /** Id */
            id: number | null;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Authors */
            authors: string | null;
            /** Section */
            section: string | null;
            /** Published At */
            published_at: string | null;
            /** Body */
            body: string | null;
            /** Main Topic */
            main_topic: string | null;
            /** Topic Keywords */
            topic_keywords: string | null;
            /** Overall Sentiment */
            overall_sentiment: string | null;
            /** Sentiment Score */
            sentiment_score: number | null;
            /** Framing */
            framing: string | null;
            /** Headline Intent */
            headline_intent: string | null;
            /** Lead Orientation */
            lead_orientation: string | null;
            /** Dominant Actor */
            dominant_actor: string | null;
            /** Source Quality */
            source_quality: string | null;
            /** Has Hard Data */
            has_hard_data: boolean | null;
            /** Blamed Actor */
            blamed_actor: string | null;
            /** Credited Actor */
            credited_actor: string | null;
            /** Sentiment Basis */
            sentiment_basis: string | null;
            /** Facts Sentiment */
            facts_sentiment: string | null;
            /** Quoted Sentiment */
            quoted_sentiment: string | null;
            /** Media Stance */
            media_stance: string | null;
            /** Media Stance Evidence */
            media_stance_evidence: string | null;
            /** Overall Sentiment Reason */
            overall_sentiment_reason: string | null;
            /** Content Flags */
            content_flags: string | null;
            /** Analyzer Name */
            analyzer_name: string | null;
            /** Analyzer Model */
            analyzer_model: string | null;
            /** Analyzer Version */
            analyzer_version: string | null;
            /** Analysis Schema Version */
            analysis_schema_version: number | null;
            /** Analyzed At */
            analyzed_at: string | null;
            /**
             * Entities
             * @default []
             */
            entities: components["schemas"]["AnalyzePreviewEntity"][];
        };
        /**
         * ArticleDetail
         * @description Reporte completo YA guardado, con sus entidades: respuesta de
         *     POST /api/articles y GET/PUT /api/articles/{id}. Distinto del schema de
         *     vista previa de POST /api/analyze (`AnalyzeResult`, más abajo): acá `id` y
         *     `body` son siempre reales, nunca `null` (esquema separado por caso de uso
         *     en vez de una sola clase compartida con campos opcionales según quién
         *     llame).
         */
        ArticleDetail: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Authors */
            authors: string | null;
            /** Section */
            section: string | null;
            /** Published At */
            published_at: string | null;
            /** Body */
            body: string;
            /** Main Topic */
            main_topic: string | null;
            /** Topic Keywords */
            topic_keywords: string | null;
            /** Overall Sentiment */
            overall_sentiment: string | null;
            /** Sentiment Score */
            sentiment_score: number | null;
            /** Framing */
            framing: string | null;
            /** Headline Intent */
            headline_intent: string | null;
            /** Lead Orientation */
            lead_orientation: string | null;
            /** Dominant Actor */
            dominant_actor: string | null;
            /** Source Quality */
            source_quality: string | null;
            /** Has Hard Data */
            has_hard_data: boolean | null;
            /** Blamed Actor */
            blamed_actor: string | null;
            /** Credited Actor */
            credited_actor: string | null;
            /** Sentiment Basis */
            sentiment_basis: string | null;
            /** Facts Sentiment */
            facts_sentiment: string | null;
            /** Quoted Sentiment */
            quoted_sentiment: string | null;
            /** Media Stance */
            media_stance: string | null;
            /** Media Stance Evidence */
            media_stance_evidence: string | null;
            /** Overall Sentiment Reason */
            overall_sentiment_reason: string | null;
            /** Content Flags */
            content_flags: string | null;
            /** Analyzer Name */
            analyzer_name: string | null;
            /** Analyzer Model */
            analyzer_model: string | null;
            /** Analyzer Version */
            analyzer_version: string | null;
            /** Analysis Schema Version */
            analysis_schema_version: number | null;
            /** Analyzed At */
            analyzed_at: string | null;
            /**
             * Entities
             * @default []
             */
            entities: components["schemas"]["EntityMention"][];
        };
        /** ArticleFiltersResponse */
        ArticleFiltersResponse: {
            /** Sources */
            sources: string[];
            /** Sections */
            sections: string[];
            /** Sentiments */
            sentiments: string[];
            /** Framing */
            framing: string[];
            /** Headline Intent */
            headline_intent: string[];
            /** Lead Orientation */
            lead_orientation: string[];
            /** Source Quality */
            source_quality: string[];
        };
        /** ArticleListResponse */
        ArticleListResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["ArticleSummary"][];
        };
        /**
         * ArticleSummary
         * @description Fila de GET /api/articles: sin cuerpo ni entidades detalladas.
         */
        ArticleSummary: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Section */
            section: string | null;
            /** Published At */
            published_at: string | null;
            /**
             * Scraped At
             * Format: date-time
             */
            scraped_at: string;
            /** Main Topic */
            main_topic: string | null;
            /** Overall Sentiment */
            overall_sentiment: string | null;
            /** Sentiment Score */
            sentiment_score: number | null;
            /** Framing */
            framing: string | null;
            /** Headline Intent */
            headline_intent: string | null;
            /** Lead Orientation */
            lead_orientation: string | null;
            /** Source Quality */
            source_quality: string | null;
            /** Has Hard Data */
            has_hard_data: boolean | null;
            /** Dominant Actor */
            dominant_actor: string | null;
            /** Blamed Actor */
            blamed_actor: string | null;
            /** Credited Actor */
            credited_actor: string | null;
            /**
             * Entity Count
             * @default 0
             */
            entity_count: number;
        };
        /**
         * ArticleUpdatePayload
         * @description Corrige el análisis (no el contenido escrapeado) de un artículo ya
         *     guardado: solo los campos que produce el analizador, nunca `title`/`body`/
         *     `url` (eso es lo que decía la fuente, no un juicio del sistema).
         */
        ArticleUpdatePayload: {
            /** Main Topic */
            main_topic?: string | null;
            /** Topic Keywords */
            topic_keywords?: string | null;
            /** Overall Sentiment */
            overall_sentiment?: string | null;
            /** Sentiment Score */
            sentiment_score?: number | null;
            /** Framing */
            framing?: string | null;
            /** Headline Intent */
            headline_intent?: string | null;
            /** Lead Orientation */
            lead_orientation?: string | null;
            /** Dominant Actor */
            dominant_actor?: string | null;
            /** Source Quality */
            source_quality?: string | null;
            /** Has Hard Data */
            has_hard_data?: boolean | null;
            /** Blamed Actor */
            blamed_actor?: string | null;
            /** Credited Actor */
            credited_actor?: string | null;
        };
        /** CanonicalEntityArticleMention */
        CanonicalEntityArticleMention: {
            /** Article Id */
            article_id: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Published At */
            published_at: string | null;
            /** Sentiment Toward */
            sentiment_toward: string | null;
            /** Sentiment Score */
            sentiment_score: number | null;
            /** Mentions Count */
            mentions_count: number;
        };
        /** CanonicalEntityDetailResponse */
        CanonicalEntityDetailResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Article Count
             * @default 0
             */
            article_count: number;
            /**
             * Total Mentions
             * @default 0
             */
            total_mentions: number;
            /** Articles */
            articles: components["schemas"]["CanonicalEntityArticleMention"][];
        };
        /** CanonicalEntityListResponse */
        CanonicalEntityListResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["CanonicalEntityResponse"][];
        };
        /** CanonicalEntityMergePayload */
        CanonicalEntityMergePayload: {
            /**
             * Source Id
             * @description Se funde DENTRO del {id} de la URL; la fuente se borra.
             */
            source_id: number;
        };
        /** CanonicalEntityResponse */
        CanonicalEntityResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Article Count
             * @default 0
             */
            article_count: number;
            /**
             * Total Mentions
             * @default 0
             */
            total_mentions: number;
        };
        /** CanonicalEntityUpdatePayload */
        CanonicalEntityUpdatePayload: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** CrawlRunResponse */
        CrawlRunResponse: {
            /** Id */
            id: number;
            /** Correlation Id */
            correlation_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Sources */
            sources: string | null;
            /** Analyzer Name */
            analyzer_name: string | null;
            /** Articles Discovered */
            articles_discovered: number;
            /** Articles Saved */
            articles_saved: number;
            /** Articles Failed */
            articles_failed: number;
            /** Stats By Source */
            stats_by_source: string | null;
            /** Error */
            error: string | null;
        };
        /** EntityAliasResponse */
        EntityAliasResponse: {
            /** Id */
            id: number;
            /** Alias */
            alias: string;
            /** Canonical Name */
            canonical_name: string;
            /** Type */
            type: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EntityMention
         * @description Una mención de entidad de un artículo YA guardado: `id` es siempre la
         *     fila real de `Entity` (nunca preview). Ver `AnalyzePreviewEntity` para la
         *     vista previa sin guardar de POST /api/analyze.
         */
        EntityMention: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Mentions Count */
            mentions_count: number;
            /** Sentiment Toward */
            sentiment_toward: string | null;
            /** Sentiment Score */
            sentiment_score: number | null;
            /** Context */
            context: string | null;
            /** Extraction Confidence */
            extraction_confidence: number;
            /** Canonical Entity Id */
            canonical_entity_id: number | null;
        };
        /** EntityPayload */
        EntityPayload: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Mentions Count
             * @default 1
             */
            mentions_count: number;
            /** Sentiment Toward */
            sentiment_toward?: string | null;
            /** Sentiment Score */
            sentiment_score?: number | null;
            /** Context */
            context?: string | null;
            /**
             * Extraction Confidence
             * @default 1
             */
            extraction_confidence: number;
        };
        /**
         * EntityUpdatePayload
         * @description Corrige una mención puntual (nombre mal extraído, sentimiento mal
         *     inferido...) sin tener que borrar y re-analizar todo el artículo.
         */
        EntityUpdatePayload: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /** Sentiment Toward */
            sentiment_toward?: string | null;
            /** Sentiment Score */
            sentiment_score?: number | null;
            /** Context */
            context?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** JobResponse */
        JobResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Stage */
            stage?: string | null;
            /** Error */
            error?: string | null;
            result?: components["schemas"]["AnalyzeResult"] | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Username */
            username: string;
        };
        /** SaveArticleRequest */
        SaveArticleRequest: {
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Authors */
            authors?: string | null;
            /** Section */
            section?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Body */
            body: string;
            /** Main Topic */
            main_topic?: string | null;
            /** Topic Keywords */
            topic_keywords?: string | null;
            /** Overall Sentiment */
            overall_sentiment?: string | null;
            /** Sentiment Score */
            sentiment_score?: number | null;
            /** Framing */
            framing?: string | null;
            /** Headline Intent */
            headline_intent?: string | null;
            /** Lead Orientation */
            lead_orientation?: string | null;
            /** Dominant Actor */
            dominant_actor?: string | null;
            /** Source Quality */
            source_quality?: string | null;
            /** Has Hard Data */
            has_hard_data?: boolean | null;
            /** Blamed Actor */
            blamed_actor?: string | null;
            /** Credited Actor */
            credited_actor?: string | null;
            /** Sentiment Basis */
            sentiment_basis?: string | null;
            /** Facts Sentiment */
            facts_sentiment?: string | null;
            /** Quoted Sentiment */
            quoted_sentiment?: string | null;
            /** Media Stance */
            media_stance?: string | null;
            /** Media Stance Evidence */
            media_stance_evidence?: string | null;
            /** Overall Sentiment Reason */
            overall_sentiment_reason?: string | null;
            /** Content Flags */
            content_flags?: string | null;
            /**
             * Entities
             * @default []
             */
            entities: components["schemas"]["EntityPayload"][];
        };
        /** ScrapeJobAccepted */
        ScrapeJobAccepted: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
        };
        /** ScrapeJobResponse */
        ScrapeJobResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Target */
            target: number;
            /** Per Source Cap */
            per_source_cap: number;
            /** Analyzer */
            analyzer: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Progress */
            progress: {
                [key: string]: components["schemas"]["ScrapeSourceProgress"];
            };
            crawl_run?: components["schemas"]["CrawlRunResponse"] | null;
            /** Error */
            error?: string | null;
        };
        /** ScrapeJobStartRequest */
        ScrapeJobStartRequest: {
            /**
             * Target
             * @default 250
             */
            target: number;
            /** Per Source Cap */
            per_source_cap?: number | null;
            /**
             * Analyzer
             * @default local
             * @enum {string}
             */
            analyzer: "local" | "groq" | "hybrid";
        };
        /** ScrapeSourceProgress */
        ScrapeSourceProgress: {
            /** Source */
            source: string;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Detail */
            detail: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResult"] | components["schemas"]["AnalyzeAccepted"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_api_articles_get: {
        parameters: {
            query?: {
                q?: string | null;
                source?: string[] | null;
                sentiment?: string | null;
                framing?: string | null;
                headline_intent?: string | null;
                lead_orientation?: string | null;
                source_quality?: string | null;
                has_hard_data?: boolean | null;
                entity?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_article_api_articles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveArticleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    article_filters_api_articles_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleFiltersResponse"];
                };
            };
        };
    };
    get_article_api_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_article_api_articles__article_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleUpdatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_article_api_articles__article_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entity_api_entities__entity_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityUpdatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityMention"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entity_api_entities__entity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_aliases_api_aliases_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityAliasResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alias_api_aliases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AliasPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityAliasResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alias_api_aliases__alias_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AliasUpdatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityAliasResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alias_api_aliases__alias_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_canonical_entities_api_canonical_entities_get: {
        parameters: {
            query?: {
                q?: string | null;
                type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalEntityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_canonical_entity_api_canonical_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalEntityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_canonical_entity_api_canonical_entities__entity_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanonicalEntityUpdatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalEntityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_canonical_entities_api_canonical_entities__entity_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanonicalEntityMergePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalEntityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_crawl_runs_api_crawl_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scrape_jobs_api_scrape_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeJobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_scrape_job_api_scrape_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScrapeJobStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeJobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scrape_job_api_scrape_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scrape_job_api_scrape_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
